### ISSUE TITLE
Crash with Hyprland v0.40.0 and above

### ISSUE THREAD

**Issue by ENDERZOMBI102** [ulinja/hyprpy#15]
After updating Hyprland, i noticed that my workspaces shortcuts were no longer working; doing investigations on my script for it revealed that the culprit was a crash caused by `EventSocket` and `CommandSocket` initialization, as their assumption on where the sockets are located on the file system has become invalid since [this commit](https://github.com/hyprwm/Hyprland/commit/a5a648091760ac002120fab18247e5292b6482de).

**Comment by ulinja** [comment]
Hi @ENDERZOMBI102 thank you very much for letting me know and filing a PR! I will look into it and review as soon as I can.

**Comment by Nama** [comment]
Just noticed, too, that my scripts aren't working now.

The new path needs to be looked up this way: `$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock`
https://wiki.hyprland.org/IPC/#xdg_runtime_dirhyprhissocket2sock
