### ISSUE TITLE
Merge with https://github.com/hyprland-community/hyprland-py?

### ISSUE THREAD

**Issue by georgetian3** [ulinja/hyprpy#4]
I was recently searching for Hyprland Python bindings and saw both this repo and [hyprland-community/hyprland-py](https://github.com/hyprland-community/hyprland-py). I haven't had the chance to take a deep look at either repo yet but I was wondering if you have considered merging your project with theirs so that there is no effort wasted on doing the same thing twice, and any unique features of either project is available to all?

**Comment by ulinja** [comment]
Hey @georgetian3,

Thanks for pointing that out! I was also looking for python bindings and came across `hyprland-py`. It's very cool, but it mostly feels like a direct wrapper for hyprctl commands. There is also sadly no documentation for it, making it difficult to actually use. With hyprpy, I'm aiming for something that's simple and very intuitive to use for devs, backed by solid documentation.

The utlimate goal is abstracting away having to write any hyprctl commands or event listeners yourself. Please do take a peek at [hyprpy's documentation](https://hyprpy.lobbes.dev/hyprpy.components.html), and you'll see what I mean.

It's early days of course, but in terms of features, I am absolutely taking inspiration from `hyprland-py` and other hyprland binding libraries.

Appreciate your input and always open to more feedback!
