### ISSUE TITLE
Error in Components Guide: Reacting to events

### ISSUE THREAD

**Issue by ChristopherEverett** [ulinja/hyprpy#8]
I'm not sure if this is the best place to discuss this or not, but I ran into an issue while following the Components Guide. Under "Reacting to events" you give this example script:

```
from hyprpy import Hyprland
from hyprpy.utils.shell import run_or_fail

instance = Hyprland()

def workspace_changed(sender, **kwargs):
   # Retrieve the newly active workspace from the signal's data
   active_workspace = kwargs.get('active_workspace')
   run_or_fail(["notify-send", "Workspace Changed", f"Workspace is now {active_workspace.id}"])

instance.signal_active_workspace_changed.connect(workspace_changed)
instance.watch()
```
On line 8 kwargs.get is expecting to receive 'active_workspace', but when this code is ran and the workspace is changed it returns None. Then in the table below you list the signal data that can be received, which does not include 'active_workspace' or 'active_workspace.id'

I was able to get the script to work correctly by changing line 8 to ```active_workspace = kwargs.get('active_workspace_id')```

I wouldn't be surprised if this was due to a change in Hyprland, but I thought you would like to know. Please let me know if there is a better way of addressing issues like this as I work with your documentation.

**Comment by ulinja** [comment]
Hi @ChristopherEverett
thank you very much for filing an issue and pointing this out to me! This is indeed the right place for this kind of thing :ok_man:

This was actually my fault: a while back I changed the the return data of that signal from being a `Workspace` object to being an `int`. I forgot to update the guide accordingly. I've fixed it now and the docs will be updated.
