### ISSUE TITLE
Docs link on PyPI incorrect (server not found)

### ISSUE THREAD

**Issue by RedBearAK** [ulinja/hyprpy#9]
@ulinja 

The link from the PyPI page for `hyprpy` seems to be incorrect: 

```sh
https://hyprpy.docs.lobbes.dev/
```

This produces a server not found error in the browser. 

Might want to go over there and change it to the working URL that I see on your repo:

```sh
https://hyprpy.lobbes.dev/
```

**Comment by ulinja** [comment]
Hi @RedBearAK 

thanks a lot for pointing this out, will be fixed in the next release!
